spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_recipes_dev
    username: spring_recipes_dev_user
    password: mihailo
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true